### ISSUE TITLE
registry doesn't use local persistent volume

### ISSUE THREAD

**Issue by adyatlov** [dcos/examples#177] opened 2017-06-13 01:08 UTC
Even if persistence is enabled during the installation, it won't take effect. The final service definition will end up with the following section:

```
...
  "env": {
        "STORAGE_PATH": "/var/lib/registry"
...
```

Which is wrong for two reasons:

1. The name of the environment variable changed to `REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY` when Docker developed a new version of the registry.
2. The value should point to the directory inside the local persistent volume directory which is inside the Mesos sandbox directory.

The section of the service definition above should look like:

```
...
  "env": {
        "REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY": "/mnt/mesos/sandbox/var/registry"
...
```

Thank you!
=Andrey

**Comment by ryadav88** [comment] 2017-06-13 16:54
@fernandosanchezmunoz to take a look as he wrote the registry package.

**Comment by fernandosanchezmunoz** [comment] 2017-06-13 17:56
I just tested the default configuration (obtained from the Universe package when marking external storage) with EBS volumes on Amazon through Rexray and it works for me.

On your comments:

- The path is mounted in the external volume as absolute "/var/lib/registry" so it can be accessed directly in the environment variable.

- the registry version in the package is 2.5.1, and the variable STORAGE_PATH seems to work correctly on that one.

@adyatlov  can you please detail the steps followed to reproduce the error you're seeing? 

Anyway, a PR is always welcome if you want to update to a more recent version and change the environment variable accordingly.

Thanks!

**Comment by adyatlov** [comment] 2017-06-15 09:57
Hi @fernandosanchezmunoz, thank you for the response! 

The steps are the following:

1. Install the Registry package from Universe using the Advanced installation. Check storage/persistence/ENABLED checkbox in the advanced installation form.
2. Push some image to the registry.
3. SSH to the node where the Registry task is running.
4. Find the task Docker ID: docker `docker ps | grep registry` and stop it: `docker stop <registry task ID>`.
EXPECTED == OBSERVED:
DC/OS starts a new task of the registry service.
5. Pull the image from the registry.
EXPECTED:
The image is found.
OBSERVED:
The image is not found.

If you change the service definition as I suggested in the original bug description, the problem is gone.

Thank you!
=Andrey

**Comment by fernandosanchezmunoz** [comment] 2017-06-15 13:41
Can you please confirm this is with persistent *local* volumes and not with persistent *external* volumes?

**Comment by adyatlov** [comment] 2017-06-16 11:28
@fernandosanchezmunoz, I reproduced the issue with Local Persistent Volumes.

**Comment by fernandosanchezmunoz** [comment] 2017-06-19 21:39
@ryadav88 @adyatlov this is addressed here: https://github.com/mesosphere/universe/pull/1233

As per Andrey's suggestions, we swap out the environment variable to 
"REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY": "/mnt/mesos/sandbox/var/registry"
if the user selects "persistent storage" but doesn't select "external persistent storage".

**Comment by ryadav88** [comment] 2017-06-25 02:14
Universe PR https://github.com/mesosphere/universe/pull/1233 merged.

**Closed by ryadav88** 2017-06-25 02:14 UTC
